version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: dev-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sites/aikalavya-only.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-app-network

networks:
  shared-app-network:
    external: true
