server {
    listen 80;
    server_name aikalavya.com;

    return 301 https://aikalavya.com$request_uri;
}

server {
    listen 443 ssl;
    server_name aikalavya.com;

    ssl_certificate /etc/letsencrypt/live/aikalavya.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aikalavya.com/privkey.pem;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream_newedluminauserfrontend newedluminauserfrontend;
        proxy_pass http://$upstream_newedluminauserfrontend:8104;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream_newedluminauserbackend newedluminauserbackend;
        proxy_pass http://$upstream_newedluminauserbackend:8202/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
