server {
    listen 80;
    server_name dps.wizzgeeks.com;
    client_max_body_size 20M;

    location / {
        proxy_pass http://dpsfrontend:3001;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream_dpsbackend dpsbackend;
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://$upstream_dpsbackend:7202; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
